use core::arch::asm;
use core::arch::global_asm;

global_asm!(include_str!("idt.S"));

pub const VECTOR_IRQ_BASE: u32 = 48;

pub fn init() {
    let idtr = Idtr {
        limit: (core::mem::size_of::<[IdtEntry; 256]>() - 1) as u16,
        base: IDT.as_ptr() as u64,
    };

    unsafe {
        asm!("lidt [{}]", in(reg) &idtr);
    }
}

#[repr(C, packed)]
struct Idtr {
    limit: u16,
    base: u64,
}

#[repr(C, packed)]
struct IdtEntry {
    offset0: u16,
    segment: u16,
    attrs: u16,
    offset1: u16,
    offset2: u32,
    reserved: u32,
}

impl IdtEntry {
    pub const fn new(handler: usize) -> Self {
        Self {
            offset0: (handler & 0xffff) as u16,
            segment: 8,    // KERNEL_CS
            attrs: 0x8e00, // Present, DPL=0, 64-bit interrupt gate, IST=0
            offset1: ((handler >> 16) & 0xffff) as u16,
            offset2: ((handler >> 32) & 0xffffffff) as u32,
            reserved: 0,
        }
    }
}
#[repr(transparent)]
struct Handler([u8; 16]);

extern "C" {
    static interrupt_handlers: [Handler; 256];
}

// TODO: Build IDT in compile time. Maybe using assembly macros?
static IDT: spin::Lazy<[IdtEntry; 256]> = spin::Lazy::new(|| {
    [
        IdtEntry::new(unsafe { &interrupt_handlers[0] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[1] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[2] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[3] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[4] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[5] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[6] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[7] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[8] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[9] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[10] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[11] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[12] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[13] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[14] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[15] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[16] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[17] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[18] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[19] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[20] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[21] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[22] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[23] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[24] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[25] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[26] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[27] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[28] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[29] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[30] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[31] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[32] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[33] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[34] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[35] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[36] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[37] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[38] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[39] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[40] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[41] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[42] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[43] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[44] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[45] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[46] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[47] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[48] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[49] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[50] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[51] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[52] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[53] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[54] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[55] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[56] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[57] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[58] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[59] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[60] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[61] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[62] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[63] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[64] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[65] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[66] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[67] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[68] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[69] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[70] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[71] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[72] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[73] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[74] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[75] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[76] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[77] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[78] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[79] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[80] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[81] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[82] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[83] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[84] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[85] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[86] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[87] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[88] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[89] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[90] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[91] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[92] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[93] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[94] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[95] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[96] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[97] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[98] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[99] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[100] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[101] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[102] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[103] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[104] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[105] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[106] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[107] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[108] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[109] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[110] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[111] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[112] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[113] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[114] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[115] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[116] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[117] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[118] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[119] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[120] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[121] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[122] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[123] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[124] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[125] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[126] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[127] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[128] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[129] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[130] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[131] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[132] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[133] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[134] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[135] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[136] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[137] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[138] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[139] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[140] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[141] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[142] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[143] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[144] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[145] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[146] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[147] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[148] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[149] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[150] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[151] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[152] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[153] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[154] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[155] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[156] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[157] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[158] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[159] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[160] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[161] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[162] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[163] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[164] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[165] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[166] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[167] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[168] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[169] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[170] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[171] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[172] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[173] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[174] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[175] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[176] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[177] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[178] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[179] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[180] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[181] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[182] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[183] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[184] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[185] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[186] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[187] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[188] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[189] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[190] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[191] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[192] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[193] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[194] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[195] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[196] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[197] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[198] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[199] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[200] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[201] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[202] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[203] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[204] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[205] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[206] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[207] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[208] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[209] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[210] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[211] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[212] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[213] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[214] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[215] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[216] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[217] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[218] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[219] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[220] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[221] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[222] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[223] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[224] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[225] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[226] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[227] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[228] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[229] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[230] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[231] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[232] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[233] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[234] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[235] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[236] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[237] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[238] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[239] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[240] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[241] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[242] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[243] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[244] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[245] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[246] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[247] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[248] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[249] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[250] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[251] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[252] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[253] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[254] as *const _ as usize }),
        IdtEntry::new(unsafe { &interrupt_handlers[255] as *const _ as usize }),
    ]
});
