//! DO NOT EDIT: This file is auto-generated by ftl_idlc.
#![no_std]

pub use ftl_autogen::*;

pub mod apps {
    
    pub mod ping {
        #[repr(C)]
        pub struct Environ {
            pub depends: Depends,
        }

        #[repr(C)]
        pub struct Depends {
            
            pub ping_server: Option<ftl_api::channel::Channel>,
            
        }
    }
    
    pub mod pong {
        #[repr(C)]
        pub struct Environ {
            pub depends: Depends,
        }

        #[repr(C)]
        pub struct Depends {
            
        }
    }
    
}