[package]
name = "boot_riscv64"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "boot_riscv64"
path = "main.rs"

[dependencies]
ftl_kernel = { workspace = true }
ftl_utils = { workspace = true }
ftl_inlinedvec = { workspace = true }
