# Caches Cargo dependencies and build artifacts.
#
# Avoid using this action for release builds and build from scratch instead!
name: "Cargo cache"

runs:
  using: composite
  steps:
  - uses: actions/cache@v6
    with:
      path: |
        ~/.cargo/registry/index
        ~/.cargo/registry/cache
        ~/.cargo/git/db
        target
      key: cargo-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      restore-keys: |
        cargo-${{ runner.os }}-${{ github.ref_name }}-
        cargo-${{ runner.os }}-main-
