mod boot;
mod console;
mod cpuvar;
mod gdt;
mod idle;
mod idt;
mod io_apic;
mod ioport;
mod local_apic;
mod mp_table;
mod msr;
mod multiboot;
mod pic;
mod pvh;
mod semihosting;
mod syscall;
mod thread;
mod timer;
mod vmspace;

pub const NUM_CPUS_MAX: usize = 8;

pub use console::console_write;
pub use cpuvar::CpuVar;
pub use cpuvar::get_cpuvar;
pub use cpuvar::set_cpuvar;
pub use idle::idle;
// pub use semihosting::semihosting_exit;
pub use thread::Thread;
pub use vmspace::DIRECT_MAP_END;
pub use vmspace::MIN_PAGE_SIZE;
pub use vmspace::VmSpace;
pub use vmspace::get_kernel_reserved_range;
pub use vmspace::paddr2vaddr;
