[package]
name = "virtio_blk_app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "virtio_blk_app"
path = "main.rs"

[dependencies]
ftl_api = { workspace = true }
ftl_virtio = { workspace = true }
ftl_api_autogen = { workspace = true }
