[package]
name = "virtio_blk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "virtio_blk"
path = "main.rs"

[dependencies]
ftl_api = { workspace = true }
ftl_virtio = { workspace = true }
ftl_driver_utils = { workspace = true }
