use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context};
use ftl_types::spec::{FiberSpec, Spec, SpecKind};

#[derive(clap::Args)]
pub struct Args {
    #[arg(long, help = "The output directory")]
    outdir: PathBuf,
    #[arg(help = "The list of fiber names to include")]
    fiber_dirs: Vec<PathBuf>,
}

struct Fiber {
    spec: FiberSpec,
}

struct AutogenCrateGenerator<'a> {
    crate_dir: &'a Path,
    fibers: &'a [Fiber],
}

impl<'a> AutogenCrateGenerator<'a> {
    pub fn new(crate_dir: &'a Path, fibers: &'a [Fiber]) -> AutogenCrateGenerator<'a> {
        AutogenCrateGenerator { crate_dir, fibers }
    }

    fn generate_fiber(&mut self, fiber: &Fiber, dir: &Path) -> anyhow::Result<()> {
        fs::create_dir(&dir)
            .with_context(|| format!("failed to create fiber directory {}", dir.display()))?;

        let mut mod_rs = String::new();
        mod_rs.push_str("//! DO NOT EDIT - This file is automatically generated.\n");
        mod_rs.push_str("\n");
        mod_rs.push_str("pub struct Deps {\n");
        for dep in &fiber.spec.deps {
            mod_rs.push_str(&format!("    pub {}: ftl_api::channel::Channel,\n", dep));
        }
        mod_rs.push_str("}\n");

        fs::write(dir.join("mod.rs"), mod_rs)
            .with_context(|| format!("failed to create {}", dir.display()))?;

        Ok(())
    }

    fn generate_fibers(&mut self) -> anyhow::Result<()> {
        let fibers_dir = self.crate_dir.join("fibers");
        fs::create_dir_all(&fibers_dir)?;

        let mut mod_rs = String::new();
        for fiber in self.fibers {
            let name = &fiber.spec.name;
            let fiber_dir = fibers_dir.join(name);
            mod_rs.push_str(&format!("pub mod {};\n", name));
            self.generate_fiber(fiber, &fiber_dir)?;
        }

        fs::write(fibers_dir.join("mod.rs"), mod_rs).context("failed to create fibers/mod.rs")?;
        Ok(())
    }

    pub fn generate(mut self) -> anyhow::Result<()> {
        let mut lib_rs = String::new();
        lib_rs.push_str("#![no_std]\n");
        lib_rs.push_str("\n");

        lib_rs.push_str("pub mod fibers;\n");
        self.generate_fibers()?;

        let mut cargo_toml = String::new();
        cargo_toml.push_str("[package]\n");
        cargo_toml.push_str("name = \"ftl_autogen\"\n");
        cargo_toml.push_str("version = \"0.0.0\"\n");
        cargo_toml.push_str("edition = \"2021\"\n");
        cargo_toml.push_str("\n");
        cargo_toml.push_str("[lib]\n");
        cargo_toml.push_str("path = \"lib.rs\"\n");
        cargo_toml.push_str("\n");
        cargo_toml.push_str("[dependencies]\n");
        cargo_toml.push_str("ftl_api = { path = \"../../api\" }\n");

        fs::write(self.crate_dir.join("lib.rs"), lib_rs).context("failed to create lib.rs")?;
        fs::write(self.crate_dir.join("Cargo.toml"), cargo_toml)
            .context("failed to create Cargo.toml")?;

        Ok(())
    }
}

struct LoaderCrateGenerator<'a> {
    crate_dir: &'a Path,
    fibers: &'a [Fiber],
}

impl<'a> LoaderCrateGenerator<'a> {
    pub fn new(crate_dir: &'a Path, fibers: &'a [Fiber]) -> LoaderCrateGenerator<'a> {
        LoaderCrateGenerator { crate_dir, fibers }
    }

    pub fn generate(self) -> anyhow::Result<()> {
        let mut lib_rs = String::new();
        lib_rs.push_str("//! DO NOT EDIT - This file is automatically generated.\n");
        lib_rs.push_str("\n");
        lib_rs.push_str("#![no_std]\n");
        lib_rs.push_str("\n");
        for fiber in self.fibers {
            let name = &fiber.spec.name;
            lib_rs.push_str(&format!("fn start_{name}(environ_cstr: *const i8) {{\n"));
            lib_rs.push_str(&format!(
                "    ::ftl_api::entrypoint::fiber_entrypoint(environ_cstr, ::{name}::main);\n"
            ));
            lib_rs.push_str("}\n");
            lib_rs.push_str("\n");
        }
        lib_rs.push_str("\n");
        lib_rs.push_str("pub const FIBER_INITS: &[fn(*const i8)] = &[");
        lib_rs.push_str(
            self.fibers
                .iter()
                .map(|fiber| format!("start_{}", fiber.spec.name))
                .collect::<Vec<String>>()
                .join(", ")
                .as_str(),
        );
        lib_rs.push_str("];\n");

        let mut cargo_toml = String::new();
        cargo_toml.push_str("[package]\n");
        cargo_toml.push_str("name = \"ftl_loader\"\n");
        cargo_toml.push_str("version = \"0.0.0\"\n");
        cargo_toml.push_str("edition = \"2021\"\n");
        cargo_toml.push_str("\n");
        cargo_toml.push_str("[lib]\n");
        cargo_toml.push_str("path = \"lib.rs\"\n");
        cargo_toml.push_str("\n");
        cargo_toml.push_str("[dependencies]\n");
        cargo_toml.push_str("ftl_api = { path = \"../../api\" }\n");
        for fiber in self.fibers {
            cargo_toml.push_str(&format!(
                "{name} = {{ path = \"../../fibers/{name}\" }}\n",
                name = fiber.spec.name
            ));
        }

        fs::write(self.crate_dir.join("lib.rs"), lib_rs).context("failed to create lib.rs")?;
        fs::write(self.crate_dir.join("Cargo.toml"), cargo_toml)
            .context("failed to create Cargo.toml")?;

        Ok(())
    }
}

pub fn main(args: &Args) -> anyhow::Result<()> {
    if !args.outdir.exists() {
        bail!("{} does not exist", args.outdir.display());
    }

    let mut fibers: Vec<Fiber> = Vec::with_capacity(args.fiber_dirs.len());
    for dir in &args.fiber_dirs {
        let spec_file_path = dir.join("spec.yaml");
        let spec_file = fs::File::open(&spec_file_path).with_context(|| {
            format!(
                "failed to open fiber spec file {}",
                spec_file_path.display()
            )
        })?;

        let spec: Spec = serde_yaml::from_reader(spec_file).with_context(|| {
            format!(
                "failed to parse fiber spec file {}",
                spec_file_path.display()
            )
        })?;

        let fiber_spec = match spec.spec {
            SpecKind::Fiber(fiber_spec) => fiber_spec,
            // _ => bail!("expected fiber spec, found {:?}", spec.spec),
        };

        if fibers.iter().any(|f| f.spec.name == fiber_spec.name) {
            bail!(
                "{}: duplicate fiber name: {}",
                spec_file_path.display(),
                fiber_spec.name
            );
        }

        fibers.push(Fiber { spec: fiber_spec });
    }

    let autogen_dir = tempfile::TempDir::new()?;
    AutogenCrateGenerator::new(autogen_dir.path(), &fibers).generate()?;

    let loader_dir = tempfile::TempDir::new()?;
    LoaderCrateGenerator::new(loader_dir.path(), &fibers).generate()?;

    for (src, dst) in &[
        (autogen_dir.path(), args.outdir.join("ftl_autogen")),
        (loader_dir.path(), args.outdir.join("ftl_loader")),
    ] {
        let _ = fs::remove_dir_all(dst);

        fs::rename(src, dst)
            .with_context(|| format!("failed to move the created crate to {}", dst.display()))?;
    }

    Ok(())
}
