//! DO NOT EDIT - This file is automatically generated.

#![no_std]

fn start_riscv_plic(environ_cstr: *const i8) {
    ::ftl_api::entrypoint::fiber_entrypoint(environ_cstr, ::riscv_plic::main);
}


pub const KERNEL_FIBERS: &[(&str, fn(*const i8))] = &[(r#"{"name":"riscv_plic","deps":[],"device_tree":[{"compatible":"sifive,plic-1.0.0"}]}"#, start_riscv_plic)];
