//! DO NOT EDIT - This file is automatically generated.

use serde::Deserialize;

#[derive(Deserialize)]
pub struct Deps {
#[serde(deserialize_with = "ftl_api::channel::deserialize_from_handle_id")]
    pub autopilot: ftl_api::channel::Channel,
}
