name: CI

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu_build:
    name: "Build (Ubuntu)"
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v5
    # TODO: Remove Zig once we don't need hello.c program for testing
    - run: sudo apt-get update && sudo apt-get install -y zig
    - name: Build World
      run: ./build.sh

  macos_build:
    name: "Build (macOS)"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    # TODO: Remove Zig once we don't need hello.c program for testing
    - run: brew install zig
    - name: Build World
      run: ./build.sh
