name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu_build:
    name: "Build (Ubuntu)"
    runs-on: ubuntu-26.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./.github/actions/cargo-cache
    # TODO: Remove Zig once we don't need hello.c program for testing
    - run: sudo apt-get update && sudo apt-get install -y zig
    - name: Build World
      run: ./build.sh

  macos_build:
    name: "Build (macOS)"
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./.github/actions/cargo-cache
    # TODO: Remove Zig once we don't need hello.c program for testing
    - run: brew install zig
    - name: Build World
      run: ./build.sh
